DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Reservation;
DROP TABLE IF EXISTS Loan;
DROP TABLE IF EXISTS Book_keywords;
DROP TABLE IF EXISTS Keyword;
DROP TABLE IF EXISTS Book_categories;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Book_authors;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Book_Copies;
DROP TABLE IF EXISTS Book;

ALTER TABLE School DROP FOREIGN KEY IF EXISTS School_ibfk_1;
ALTER TABLE School DROP FOREIGN KEY IF EXISTS School_ibfk_2;
ALTER TABLE User DROP FOREIGN KEY IF EXISTS User_ibfk_1;
DROP TABLE IF EXISTS School;
DROP TABLE IF EXISTS User;